# Generated by Django 3.0.6 on 2020-08-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default='/static/music/images/avatar_2x.png', upload_to=''),
        ),
    ]
