# Generated by Django 3.0.6 on 2020-08-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200816_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default='settings.STATIC_ROOT/music/images/avatar_2x.png', upload_to=''),
        ),
    ]
